project_id = "pdzxhcbykhtubcjhinwy"

[functions.analyze-crop]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.expert-chat]
verify_jwt = false

[functions.expert-chat-agent]
verify_jwt = false
